-- TASK_145 (Phase 5) — self-hosted product licence: revocation storage + the
-- self-hosted OS price field.
--
-- ADDITIVE ONLY: one CREATE TABLE (ExeLicenseRevocation) + its two indexes + two
-- FKs, and one ADD COLUMN ... NOT NULL DEFAULT 0 on AdminSetting. No existing
-- row, column, constraint or index is dropped, altered or renamed.
--
-- Generated by Prisma from the datamodel change alone:
--   git show HEAD:prisma/schema.prisma > /tmp/schema_base.prisma
--   npx prisma migrate diff --from-schema-datamodel /tmp/schema_base.prisma \
--     --to-schema-datamodel prisma/schema.prisma --script
-- Both migration commands are blocked on this checkout by PRE-EXISTING defects
-- that are NOT part of T1 (verified 2026-09-29; full raw output in the TASK_145
-- log, both tracks):
--   * `migrate dev`  -> P3006 / P1014: the SHADOW-db replay dies at
--       20260914150000_add_license_claim_token ("The underlying table for
--       model `ExeLicense` does not exist") — a replay-ordering defect in the
--       historical migration folder.
--   * `migrate deploy|status` on the real DB -> P3009: `_prisma_migrations`
--       has a row for 20260921000000_device_tools_v2 with finished_at IS NULL
--       (started 2026-09-29 02:01:47 UTC, before this task).
-- Resolving either is another task's job. This file was therefore produced with
-- `prisma migrate diff` and validated by applying it inside a transaction and
-- rolling back (see log) — never by `migrate dev`.

-- AlterTable
ALTER TABLE "AdminSetting" ADD COLUMN     "selfhostedOsPriceUsd" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- CreateTable
CREATE TABLE "ExeLicenseRevocation" (
    "id" TEXT NOT NULL,
    "exeLicenseId" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "reason" TEXT,
    "revokedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "revokedBy" TEXT,

    CONSTRAINT "ExeLicenseRevocation_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "ExeLicenseRevocation_exeLicenseId_key" ON "ExeLicenseRevocation"("exeLicenseId");

-- CreateIndex
CREATE INDEX "ExeLicenseRevocation_userId_idx" ON "ExeLicenseRevocation"("userId");

-- AddForeignKey
ALTER TABLE "ExeLicenseRevocation" ADD CONSTRAINT "ExeLicenseRevocation_exeLicenseId_fkey" FOREIGN KEY ("exeLicenseId") REFERENCES "ExeLicense"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ExeLicenseRevocation" ADD CONSTRAINT "ExeLicenseRevocation_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
