-- TASK_156 C1 — the Cyber Lab schema + the Lab* cap family. Purely ADDITIVE: eight
-- AdminSetting columns (every one NOT NULL DEFAULT <value>) and ten new EMPTY tables.
-- Applying this rewrites NO existing row and changes NO existing behaviour — nothing
-- reads these yet (the engine is C2+, gated behind the C0 AUP and the premium
-- `cyberlab` entitlement). Same discipline as the TASK_155 P1/P2/P3 migrations.
--
--   * cyberlabConsentTermsVersion / cyberlabMaxTargetsPerUser / cyberlabMaxRunsPerDay /
--     cyberlabSentinelDnsQueriesPerMinute / cyberlabSentinelEntropyThreshold /
--     cyberlabSentinelFreezeOnRefusals / cyberlabToolStaleAfterDays /
--     cyberlabResearchRefreshDays — the §5.2 sentinel dials + the §12.1 research
--     cadence + the C0 consent-gate version (PLAN_156 §7 C1; CROSS-TASK rule: every
--     limit is a named AdminSetting field, read server-side, admin-editable, live
--     without a redeploy). ADDITIVE to the D1-P2 `cyberlab*` dials — those are NOT
--     re-created here.
--   * LabHost — a machine the engine may run on; NEVER the production VPS (§6).
--   * LabScenario — an allow-listed scenario; `author` is an AUDIENCE label (§12.9).
--   * LabRange — one run instance (the pending→…→torn_down state machine + TTL).
--   * LabTarget — THE attested inventory item (§5) — the legal spine.
--   * LabEpisode — the evidence bundle (timeline, ATT&CK mapping, signed manifest).
--   * LabFinding — a finding, with a self-relation for retest tracking.
--   * DetectionPack — a Sigma-class pack derived from an episode (C5).
--   * LabConsent — the AUP/consent record (C0); append-only, never updated.
--   * LabAbuseReport — the §5.2 sentinel's output (refusal → report → freeze).
--   * LabToolCatalog — the §12.1 research gate: one row per capability, with a
--     `staleAfter` date that HIDES a stale row from the UI automatically.
--
-- Every userId/*Id column is a plain scalar with an index and NO foreign key, on
-- purpose: a lab attestation, consent record or evidence bundle must survive the
-- deletion of the thing it describes (same rule HostingSite / AgentActionAudit use).
--
-- Hand-written SQL (HOW_WE_MOVE_FAST rule 2); column order mirrors the datamodel.
-- Generated by `prisma migrate diff --from-schema-datamodel <HEAD> --to-schema-datamodel`
-- so it is the exact additive delta, then reviewed by hand.

-- AlterTable
ALTER TABLE "AdminSetting" ADD COLUMN     "cyberlabConsentTermsVersion" TEXT NOT NULL DEFAULT '2026-10-02',
ADD COLUMN     "cyberlabMaxRunsPerDay" INTEGER NOT NULL DEFAULT 10,
ADD COLUMN     "cyberlabMaxTargetsPerUser" INTEGER NOT NULL DEFAULT 50,
ADD COLUMN     "cyberlabResearchRefreshDays" INTEGER NOT NULL DEFAULT 30,
ADD COLUMN     "cyberlabSentinelDnsQueriesPerMinute" INTEGER NOT NULL DEFAULT 600,
ADD COLUMN     "cyberlabSentinelEntropyThreshold" INTEGER NOT NULL DEFAULT 40,
ADD COLUMN     "cyberlabSentinelFreezeOnRefusals" INTEGER NOT NULL DEFAULT 3,
ADD COLUMN     "cyberlabToolStaleAfterDays" INTEGER NOT NULL DEFAULT 180;

-- CreateTable
CREATE TABLE "LabHost" (
    "id" TEXT NOT NULL,
    "label" TEXT NOT NULL,
    "kind" TEXT NOT NULL,
    "address" TEXT NOT NULL,
    "authRef" TEXT,
    "enabled" BOOLEAN NOT NULL DEFAULT false,
    "ramBudgetMb" INTEGER NOT NULL DEFAULT 2048,
    "tags" JSONB,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "LabHost_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "LabScenario" (
    "id" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "klass" TEXT NOT NULL,
    "techniqueIds" JSONB,
    "adversaryProfile" TEXT,
    "requiredCapabilities" JSONB,
    "blastRadius" TEXT,
    "cleanup" TEXT,
    "enabled" BOOLEAN NOT NULL DEFAULT false,
    "author" TEXT NOT NULL DEFAULT 'staff',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "LabScenario_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "LabRange" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "scenarioId" TEXT NOT NULL,
    "state" TEXT NOT NULL DEFAULT 'pending',
    "ttlExpiresAt" TIMESTAMP(3),
    "consentId" TEXT,
    "credentialRef" TEXT,
    "queuedSlotId" TEXT,
    "teardownVerifiedAt" TIMESTAMP(3),
    "error" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "LabRange_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "LabTarget" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "rangeId" TEXT,
    "kind" TEXT NOT NULL,
    "value" TEXT NOT NULL,
    "attestedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "attestationId" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "LabTarget_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "LabEpisode" (
    "id" TEXT NOT NULL,
    "rangeId" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "startedAt" TIMESTAMP(3),
    "endedAt" TIMESTAMP(3),
    "timeline" JSONB,
    "techniques" JSONB,
    "telemetrySignatures" JSONB,
    "outcome" TEXT,
    "evidenceManifest" JSONB,
    "signedHash" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "LabEpisode_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "LabFinding" (
    "id" TEXT NOT NULL,
    "episodeId" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "severity" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "detail" TEXT,
    "retestOf" TEXT,
    "exportedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "LabFinding_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "DetectionPack" (
    "id" TEXT NOT NULL,
    "version" TEXT NOT NULL,
    "rulesJson" JSONB NOT NULL,
    "validatedByEpisodeId" TEXT,
    "shippedAt" TIMESTAMP(3),
    "audience" TEXT NOT NULL DEFAULT 'staff',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "DetectionPack_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "LabConsent" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "termsVersion" TEXT NOT NULL,
    "scope" TEXT NOT NULL DEFAULT 'lab',
    "signedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "ip" TEXT,
    "hash" TEXT NOT NULL,

    CONSTRAINT "LabConsent_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "LabAbuseReport" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "rangeId" TEXT,
    "reason" TEXT NOT NULL,
    "evidenceJson" JSONB,
    "severity" TEXT NOT NULL DEFAULT 'low',
    "status" TEXT NOT NULL DEFAULT 'open',
    "reviewedByAdminId" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "reviewedAt" TIMESTAMP(3),

    CONSTRAINT "LabAbuseReport_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "LabToolCatalog" (
    "id" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "klass" TEXT NOT NULL,
    "kind" TEXT NOT NULL,
    "techniqueIds" JSONB,
    "upstreamVersion" TEXT,
    "upstreamReleasedAt" TIMESTAMP(3),
    "lastReviewedAt" TIMESTAMP(3),
    "staleAfter" TIMESTAMP(3),
    "cveHistory" JSONB,
    "licence" TEXT,
    "derivation" TEXT,
    "audience" TEXT NOT NULL DEFAULT 'staff',
    "legalBasis" TEXT NOT NULL,
    "enabled" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "LabToolCatalog_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "LabHost_kind_enabled_idx" ON "LabHost"("kind", "enabled");

-- CreateIndex
CREATE UNIQUE INDEX "LabScenario_slug_key" ON "LabScenario"("slug");

-- CreateIndex
CREATE INDEX "LabScenario_klass_enabled_idx" ON "LabScenario"("klass", "enabled");

-- CreateIndex
CREATE INDEX "LabRange_userId_state_idx" ON "LabRange"("userId", "state");

-- CreateIndex
CREATE INDEX "LabRange_state_ttlExpiresAt_idx" ON "LabRange"("state", "ttlExpiresAt");

-- CreateIndex
CREATE INDEX "LabTarget_userId_idx" ON "LabTarget"("userId");

-- CreateIndex
CREATE UNIQUE INDEX "LabTarget_userId_kind_value_key" ON "LabTarget"("userId", "kind", "value");

-- CreateIndex
CREATE INDEX "LabEpisode_rangeId_idx" ON "LabEpisode"("rangeId");

-- CreateIndex
CREATE INDEX "LabEpisode_userId_createdAt_idx" ON "LabEpisode"("userId", "createdAt");

-- CreateIndex
CREATE INDEX "LabFinding_episodeId_idx" ON "LabFinding"("episodeId");

-- CreateIndex
CREATE INDEX "LabFinding_retestOf_idx" ON "LabFinding"("retestOf");

-- CreateIndex
CREATE INDEX "DetectionPack_audience_idx" ON "DetectionPack"("audience");

-- CreateIndex
CREATE INDEX "LabConsent_userId_termsVersion_idx" ON "LabConsent"("userId", "termsVersion");

-- CreateIndex
CREATE INDEX "LabAbuseReport_userId_status_idx" ON "LabAbuseReport"("userId", "status");

-- CreateIndex
CREATE INDEX "LabAbuseReport_status_createdAt_idx" ON "LabAbuseReport"("status", "createdAt");

-- CreateIndex
CREATE UNIQUE INDEX "LabToolCatalog_slug_key" ON "LabToolCatalog"("slug");

-- CreateIndex
CREATE INDEX "LabToolCatalog_klass_kind_idx" ON "LabToolCatalog"("klass", "kind");

-- CreateIndex
CREATE INDEX "LabToolCatalog_enabled_staleAfter_idx" ON "LabToolCatalog"("enabled", "staleAfter");

